@Sumup.API_HostAddress = http://localhost:5039

GET {{Sumup.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Sumup.API_HostAddress}}/api/user/create-test-user
Accept: application/json

###

POST {{Sumup.API_HostAddress}}/api/user/settings
Content-Type: application/json

{
  "userId": "",
  "wakeUpTime": "21:07:00",
  "googleRefreshToken": "Token Bilgisi",
  "preferences": "Kısa ve öz olsun.Önemli şeyleri özetle ",
  "voiceId": "21m00Tcm4TlvDq8ikWAM",
  "timeZoneId": "Turkey Standard Time"
}

###
